### ISSUE TITLE
v0.1.0 to-do list

### ISSUE THREAD

**Issue by kbarbary** [kbarbary/nestle#6]
List of to-do items for release, mainly for my own benefit.

- [x] `weightedcov()` API: make it as similar as possible to `np.cov` & `np.average`.  
       *Changed name to `mean_and_cov()` for clarity.*
- [x] Result dictionary (and keys): look at scipy's `OptimizeResult`.  
       *Changed `logprior` to `logvol` for clarity.*
- [x] Think about callback API some more.  
      *Single callback function that gets passed a dictionary.*
- [x] ellipsoid partitioning interval
- [x] "classic" point exploration method
- [x] List of references
- [x] Example illustrating `prior_transform`
- [x] Implement more test cases from ellipsoidal nested sampling papers
